name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: docker build -t backend .
      
    - name: Log in to Google Cloud
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: mytest-425707
        export_default_credentials: true

    - name: Push Docker image to Google Container Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
        docker tag backend us-central1-docker.pkg.dev/mytest-425707/backend/backend:latest
        docker push us-central1-docker.pkg.dev/mytest-425707/backend/backend:latest

    - name: Deploy to Cloud Run
      run: gcloud run deploy backend --image us-central1-docker.pkg.dev/mytest-425707/backend/backend:latest --platform managed --region us-central1
