name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: docker build -t frontend .
      
    - name: Log in to Google Cloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: <project-id>

    - name: Push Docker image to Google Container Registry
      run: |
        docker tag flask-app gcr.io/<project-id>/frontend:latest
        docker push gcr.io/<project-id>/frontend:latest

    - name: Deploy to Cloud Run
      run: gcloud run deploy frontend --image gcr.io/<project-id>/frontend:latest --platform managed --region us-central1
